version: '3.8'

services:
  db:
    image: postgres:15
    container_name: taskflow_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: taskflow_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/taskflow
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: taskflow_frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  pgdata:
